type KeysEnum<T> = { [P in keyof Required<T>]: true };

// This file exists as a workaround to obtain and maintain
// a list of html and svg tag names
// https://stackoverflow.com/a/54308812

const HTMLElementTagNamesEnum: KeysEnum<HTMLElementTagNameMap> = {
  a: true,
  abbr: true,
  address: true,
  applet: true,
  area: true,
  article: true,
  aside: true,
  audio: true,
  b: true,
  base: true,
  basefont: true,
  bdi: true,
  bdo: true,
  blockquote: true,
  body: true,
  br: true,
  button: true,
  canvas: true,
  caption: true,
  cite: true,
  code: true,
  col: true,
  colgroup: true,
  data: true,
  datalist: true,
  dd: true,
  del: true,
  details: true,
  dfn: true,
  dialog: true,
  dir: true,
  div: true,
  dl: true,
  dt: true,
  em: true,
  embed: true,
  fieldset: true,
  figcaption: true,
  figure: true,
  font: true,
  footer: true,
  form: true,
  frame: true,
  frameset: true,
  h1: true,
  h2: true,
  h3: true,
  h4: true,
  h5: true,
  h6: true,
  head: true,
  header: true,
  hgroup: true,
  hr: true,
  html: true,
  i: true,
  iframe: true,
  img: true,
  input: true,
  ins: true,
  kbd: true,
  label: true,
  legend: true,
  li: true,
  link: true,
  main: true,
  map: true,
  mark: true,
  marquee: true,
  menu: true,
  meta: true,
  meter: true,
  nav: true,
  noscript: true,
  object: true,
  ol: true,
  optgroup: true,
  option: true,
  output: true,
  p: true,
  param: true,
  picture: true,
  pre: true,
  progress: true,
  q: true,
  rp: true,
  rt: true,
  ruby: true,
  s: true,
  samp: true,
  script: true,
  section: true,
  select: true,
  slot: true,
  small: true,
  source: true,
  span: true,
  strong: true,
  style: true,
  sub: true,
  summary: true,
  sup: true,
  table: true,
  tbody: true,
  td: true,
  template: true,
  textarea: true,
  tfoot: true,
  th: true,
  thead: true,
  time: true,
  title: true,
  tr: true,
  track: true,
  u: true,
  ul: true,
  var: true,
  video: true,
  wbr: true,
};
export const HTMLElementTagNames = Object.keys(
  HTMLElementTagNamesEnum,
) as Array<keyof HTMLElementTagNameMap>;
export function isHTMLElementTag(
  tag: string,
): tag is keyof HTMLElementTagNameMap {
  return tag in HTMLElementTagNamesEnum;
}

const SVGElementTagNamesEnum: KeysEnum<SVGElementTagNameMap> = {
  a: true,
  circle: true,
  clipPath: true,
  defs: true,
  desc: true,
  ellipse: true,
  feBlend: true,
  feColorMatrix: true,
  feComponentTransfer: true,
  feComposite: true,
  feConvolveMatrix: true,
  feDiffuseLighting: true,
  feDisplacementMap: true,
  feDistantLight: true,
  feFlood: true,
  feFuncA: true,
  feFuncB: true,
  feFuncG: true,
  feFuncR: true,
  feGaussianBlur: true,
  feImage: true,
  feMerge: true,
  feMergeNode: true,
  feMorphology: true,
  feOffset: true,
  fePointLight: true,
  feSpecularLighting: true,
  feSpotLight: true,
  feTile: true,
  feTurbulence: true,
  filter: true,
  foreignObject: true,
  g: true,
  image: true,
  line: true,
  linearGradient: true,
  marker: true,
  mask: true,
  metadata: true,
  path: true,
  pattern: true,
  polygon: true,
  polyline: true,
  radialGradient: true,
  rect: true,
  script: true,
  stop: true,
  style: true,
  svg: true,
  switch: true,
  symbol: true,
  text: true,
  textPath: true,
  title: true,
  tspan: true,
  use: true,
  view: true,
};
export const SVGElementTagNames = Object.keys(SVGElementTagNamesEnum) as Array<
  keyof SVGElementTagNameMap
>;
export function isSVGElementTag(
  tag: string,
): tag is keyof SVGElementTagNameMap {
  return tag in SVGElementTagNamesEnum;
}

export function isBrowserElementTag(
  tag: string,
): tag is keyof (HTMLElementTagNameMap & SVGElementTagNameMap) {
  return tag in HTMLElementTagNamesEnum || tag in SVGElementTagNamesEnum;
}
